#!/usr/bin/env bash
set -e
pip install git+https://github.com/datajoint/microns_phase3_nda#egg=microns_phase3
pip install em_coregistration@git+https://github.com/AllenInstitute/em_coregistration@phase3#egg=em_coregistration

export DJ_HOST=db.datajoint.com
export DJ_USER=microns
export DJ_PASS=microns2023
export DATABASE_PREFIX=microns_
echo 'export DJ_HOST=db.datajoint.com' >> ~/.bashrc 
echo 'export DJ_USER=microns' >> ~/.bashrc 
echo 'export DJ_PASS=microns2023' >> ~/.bashrc 
echo 'export DATABASE_PREFIX=microns_' >> ~/.bashrc 